// <auto-generated />
namespace HotelWizard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class added_AdminConfig_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_AdminConfig_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201404082036402_added_AdminConfig_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
