// <auto-generated />
namespace HotelWizard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_event_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_event_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201404260958110_add_event_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
