// <auto-generated />
namespace HotelWizard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class adding_tables_for_restaurant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_tables_for_restaurant));
        
        string IMigrationMetadata.Id
        {
            get { return "201404201946069_adding_tables_for_restaurant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
