// <auto-generated />
namespace HotelWizard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_tablenumber_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tablenumber_column));
        
        string IMigrationMetadata.Id
        {
            get { return "201404202200199_add_tablenumber_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
