// <auto-generated />
namespace HotelWizard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class change_roombooking_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_roombooking_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201404151806061_change_roombooking_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
