// <auto-generated />
namespace HotelWizard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class customer_and_roomBooking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customer_and_roomBooking));
        
        string IMigrationMetadata.Id
        {
            get { return "201404051834446_customer_and_roomBooking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
